import type {
  AdminContentSection,
  AdminContentSectionId,
  SiteContent,
} from "@/types/site-content";

type ContentRoot = Exclude<keyof SiteContent, "pageSections">;

export interface ContentFieldDefinition {
  path: [ContentRoot, string];
  label: string;
  kind?: "input" | "textarea" | "switch";
}

export const adminContentSections: AdminContentSection[] = [
  {
    id: "sections",
    name: "Secciones frontend",
    description: "Habilita, deshabilita y ordena bloques visibles en el sitio.",
    group: "system",
  },
  {
    id: "operations",
    name: "Operacion",
    description: "Control operativo para habilitar o pausar pedidos.",
    group: "system",
  },
  {
    id: "home.hero",
    name: "Hero",
    description: "Encabezado principal y CTAs de inicio.",
    group: "home",
    sectionKey: "home.hero",
  },
  {
    id: "home.featured",
    name: "Productos",
    description: "Bloque destacado de productos en inicio.",
    group: "home",
    sectionKey: "home.featured",
  },
  {
    id: "home.favorites",
    name: "Favoritos",
    description: "Mensajes del bloque de favoritos del usuario.",
    group: "home",
    sectionKey: "home.favorites",
  },
  {
    id: "home.story",
    name: "Nosotros",
    description: "Bloque editorial e historia dentro del home.",
    group: "home",
    sectionKey: "home.story",
  },
  {
    id: "home.testimonials",
    name: "Testimonios",
    description: "Testimonios mostrados en portada.",
    group: "home",
    sectionKey: "home.testimonials",
  },
  {
    id: "home.promotions",
    name: "Promociones",
    description: "Bloque promocional para crecimiento y conversion.",
    group: "growth",
    sectionKey: "home.promotions",
  },
  {
    id: "menu.header",
    name: "Hero menu",
    description: "Cabecera editorial del menu.",
    group: "menu",
    sectionKey: "menu.header",
  },
  {
    id: "menu.products",
    name: "Productos menu",
    description: "Guardados, buscador y listado del menu.",
    group: "menu",
    sectionKey: "menu.products",
  },
  {
    id: "about.page",
    name: "Pagina nosotros",
    description: "Contenido publico de la pagina nosotros.",
    group: "page",
    sectionKey: "about.page",
  },
  {
    id: "contact.page",
    name: "Pagina contacto",
    description: "Contenido publico de la pagina contacto.",
    group: "page",
    sectionKey: "contact.page",
  },
];

export const adminContentFieldRegistry: Partial<Record<AdminContentSectionId, ContentFieldDefinition[]>> = {
  operations: [
    { path: ["operations", "isOrderingEnabled"], label: "Permitir pedidos", kind: "switch" },
    { path: ["operations", "statusLabel"], label: "Estado visible" },
    { path: ["operations", "bannerText"], label: "Texto corto de estado" },
    { path: ["operations", "notice"], label: "Aviso operativo", kind: "textarea" },
    { path: ["operations", "checkoutMessage"], label: "Mensaje para checkout", kind: "textarea" },
    { path: ["operations", "transferBank"], label: "Banco transferencia" },
    { path: ["operations", "transferAccountHolder"], label: "Titular cuenta" },
    { path: ["operations", "transferAccountNumber"], label: "Numero de cuenta" },
    { path: ["operations", "transferClabe"], label: "CLABE" },
    { path: ["operations", "transferReferenceLabel"], label: "Etiqueta de referencia" },
    { path: ["operations", "transferInstructions"], label: "Instrucciones transferencia", kind: "textarea" },
  ],
  "home.hero": [
    { path: ["home", "heroBadge"], label: "Badge hero" },
    { path: ["home", "heroTitle"], label: "Titulo hero" },
    { path: ["home", "heroHighlight"], label: "Resaltado hero" },
    { path: ["home", "heroDescription"], label: "Descripcion hero", kind: "textarea" },
    { path: ["home", "heroPrimaryCtaLabel"], label: "CTA principal" },
    { path: ["home", "heroSecondaryCtaLabel"], label: "CTA secundaria" },
    { path: ["home", "heroImage"], label: "Imagen hero" },
    { path: ["home", "heroFloatingCount"], label: "Conteo flotante" },
    { path: ["home", "heroFloatingQuote"], label: "Texto flotante", kind: "textarea" },
  ],
  "home.featured": [
    { path: ["home", "featuredTitle"], label: "Titulo destacados" },
    { path: ["home", "featuredDescription"], label: "Descripcion destacados", kind: "textarea" },
    { path: ["home", "featuredCtaLabel"], label: "CTA destacados" },
  ],
  "home.favorites": [
    { path: ["home", "favoritesEyebrow"], label: "Eyebrow favoritos" },
    { path: ["home", "favoritesTitle"], label: "Titulo favoritos" },
    { path: ["home", "favoritesDescription"], label: "Descripcion favoritos", kind: "textarea" },
    { path: ["home", "favoritesCtaLabel"], label: "CTA favoritos" },
    { path: ["home", "favoritesEmptyTitle"], label: "Titulo vacio" },
    { path: ["home", "favoritesEmptyDescription"], label: "Descripcion vacio", kind: "textarea" },
  ],
  "home.story": [
    { path: ["home", "storyTitle"], label: "Titulo bloque historia" },
    { path: ["home", "storyHighlight"], label: "Resaltado bloque historia" },
    { path: ["home", "storyDescription"], label: "Descripcion bloque historia", kind: "textarea" },
    { path: ["home", "storyImage"], label: "Imagen bloque historia" },
    { path: ["home", "storyBadge"], label: "Badge bloque historia" },
    { path: ["home", "storyItemOneTitle"], label: "Item 1 titulo" },
    { path: ["home", "storyItemOneDescription"], label: "Item 1 descripcion" },
    { path: ["home", "storyItemTwoTitle"], label: "Item 2 titulo" },
    { path: ["home", "storyItemTwoDescription"], label: "Item 2 descripcion" },
    { path: ["home", "storyCtaLabel"], label: "CTA historia" },
  ],
  "home.testimonials": [
    { path: ["home", "testimonialsTitle"], label: "Titulo testimonios" },
    { path: ["home", "testimonialOneName"], label: "Testimonio 1 nombre" },
    { path: ["home", "testimonialOneText"], label: "Testimonio 1 texto", kind: "textarea" },
    { path: ["home", "testimonialOneRole"], label: "Testimonio 1 rol" },
    { path: ["home", "testimonialTwoName"], label: "Testimonio 2 nombre" },
    { path: ["home", "testimonialTwoText"], label: "Testimonio 2 texto", kind: "textarea" },
    { path: ["home", "testimonialTwoRole"], label: "Testimonio 2 rol" },
    { path: ["home", "testimonialThreeName"], label: "Testimonio 3 nombre" },
    { path: ["home", "testimonialThreeText"], label: "Testimonio 3 texto", kind: "textarea" },
    { path: ["home", "testimonialThreeRole"], label: "Testimonio 3 rol" },
  ],
  "home.promotions": [
    { path: ["promotions", "eyebrow"], label: "Eyebrow promociones" },
    { path: ["promotions", "title"], label: "Titulo promociones" },
    { path: ["promotions", "highlight"], label: "Resaltado promociones" },
    { path: ["promotions", "description"], label: "Descripcion promociones", kind: "textarea" },
    { path: ["promotions", "primaryCtaLabel"], label: "CTA promociones" },
    { path: ["promotions", "secondaryText"], label: "Texto secundario", kind: "textarea" },
    { path: ["promotions", "benefitOne"], label: "Beneficio 1" },
    { path: ["promotions", "benefitTwo"], label: "Beneficio 2" },
    { path: ["promotions", "benefitThree"], label: "Beneficio 3" },
  ],
  "menu.header": [
    { path: ["menu", "title"], label: "Titulo" },
    { path: ["menu", "highlight"], label: "Resaltado" },
    { path: ["menu", "description"], label: "Descripcion", kind: "textarea" },
    { path: ["menu", "searchPlaceholder"], label: "Placeholder buscador" },
  ],
  "menu.products": [
    { path: ["menu", "savedTitle"], label: "Titulo guardados" },
    { path: ["menu", "savedDescription"], label: "Descripcion guardados", kind: "textarea" },
    { path: ["menu", "savedEmptyTitle"], label: "Titulo vacio guardados" },
    { path: ["menu", "savedEmptyDescription"], label: "Descripcion vacio guardados", kind: "textarea" },
    { path: ["menu", "emptyStateTitle"], label: "Mensaje sin resultados", kind: "textarea" },
    { path: ["menu", "emptyStateCtaLabel"], label: "CTA sin resultados" },
  ],
  "about.page": [
    { path: ["about", "eyebrow"], label: "Eyebrow" },
    { path: ["about", "title"], label: "Titulo" },
    { path: ["about", "highlight"], label: "Resaltado" },
    { path: ["about", "introTitle"], label: "Titulo introduccion" },
    { path: ["about", "introDescriptionOne"], label: "Parrafo 1", kind: "textarea" },
    { path: ["about", "introDescriptionTwo"], label: "Parrafo 2", kind: "textarea" },
    { path: ["about", "image"], label: "Imagen principal" },
    { path: ["about", "valueOneTitle"], label: "Valor 1 titulo" },
    { path: ["about", "valueOneDescription"], label: "Valor 1 descripcion" },
    { path: ["about", "valueTwoTitle"], label: "Valor 2 titulo" },
    { path: ["about", "valueTwoDescription"], label: "Valor 2 descripcion" },
    { path: ["about", "pillarsTitle"], label: "Titulo pilares" },
    { path: ["about", "pillarsSubtitle"], label: "Subtitulo pilares" },
    { path: ["about", "pillarOneTitle"], label: "Pilar 1 titulo" },
    { path: ["about", "pillarOneDescription"], label: "Pilar 1 descripcion", kind: "textarea" },
    { path: ["about", "pillarTwoTitle"], label: "Pilar 2 titulo" },
    { path: ["about", "pillarTwoDescription"], label: "Pilar 2 descripcion", kind: "textarea" },
    { path: ["about", "pillarThreeTitle"], label: "Pilar 3 titulo" },
    { path: ["about", "pillarThreeDescription"], label: "Pilar 3 descripcion", kind: "textarea" },
  ],
  "contact.page": [
    { path: ["contact", "title"], label: "Titulo" },
    { path: ["contact", "highlight"], label: "Resaltado" },
    { path: ["contact", "description"], label: "Descripcion", kind: "textarea" },
    { path: ["contact", "infoTitle"], label: "Titulo informacion" },
    { path: ["contact", "addressLabel"], label: "Etiqueta direccion" },
    { path: ["contact", "addressValue"], label: "Direccion", kind: "textarea" },
    { path: ["contact", "phoneLabel"], label: "Etiqueta telefono" },
    { path: ["contact", "phoneValue"], label: "Telefono" },
    { path: ["contact", "emailLabel"], label: "Etiqueta email" },
    { path: ["contact", "emailValue"], label: "Email" },
    { path: ["contact", "hoursLabel"], label: "Etiqueta horario" },
    { path: ["contact", "hoursValue"], label: "Horario" },
    { path: ["contact", "mapTitle"], label: "Titulo mapa" },
    { path: ["contact", "mapCtaLabel"], label: "CTA mapa" },
    { path: ["contact", "formTitle"], label: "Titulo formulario" },
    { path: ["contact", "successTitle"], label: "Titulo exito" },
    { path: ["contact", "successDescription"], label: "Descripcion exito", kind: "textarea" },
    { path: ["contact", "submitLabel"], label: "CTA formulario" },
  ],
};
